# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMRtZAB6TS4pxX3x-1atmXs3A2GKit1R
"""

import requests
import pandas as pd

# SUA API KEY AQUI:
API_KEY = "92a41702d74e41fc85bd77effd476f44"

# Cabeçalho da requisição
headers = {'X-Auth-Token': API_KEY}

# Código do Brasileirão na API é 2013
url = "https://api.football-data.org/v4/competitions/BSA/matches"

# Requisição GET
response = requests.get(url, headers=headers)

# Verificar status
if response.status_code == 200:
    dados = response.json()
    partidas = dados['matches']

    lista_jogos = []
    for jogo in partidas:
        if jogo["status"] in ["SCHEDULED", "LIVE"]:
            item = {
                "Data": jogo["utcDate"][:10],
                "Hora": jogo["utcDate"][11:16],
                "Time A": jogo["homeTeam"]["name"],
                "Time B": jogo["awayTeam"]["name"],
                "Status": jogo["status"]
            }
            lista_jogos.append(item)

    df = pd.DataFrame(lista_jogos)
    from datetime import datetime

    # Filtrar para mostrar apenas os jogos do dia atual
    hoje = datetime.utcnow().strftime('%Y-%m-%d')  # Formato da API
    display(df)

    print("Jogos do Brasileirão (Pré-live e Ao Vivo):")
    display(df)
else:
    print("Erro ao buscar dados:", response.status_code)